

// enable 3th party plugin: https://github.com/silviomoreto/bootstrap-select (nice select plugin)
{$DEFINE IWBSBOOTSTRAPSELECT}

// enable 3th party plugin: // http://afarkas.github.io/webshim/demos/index.html (add missing html5 functionality to most browsers)
{$DEFINE IWBSWEBSHIM}

// enable 3th party plugin: https://github.com/kattunga/IWBootstrapFramework (add responsiveness to bootstrap tabs)
{$DEFINE IWBSDYNTABS}

